import { Resume, Agent, ActivityEvent, WeightPreset } from "@/types";

export const mockResumes: Resume[] = [
  {
    id: "1",
    name: "Priya Sharma",
    role: "Frontend Developer",
    initials: "PS",
    fileName: "priya_sharma_resume.pdf",
    fileSize: "1.2 MB",
    status: "processing",
    progress: 80,
    currentAgent: "ocr",
    scores: { technical: 92, experience: 85, projects: 88, culture: 90, overall: 89 },
    redFlags: [],
    skills: ["React", "TypeScript", "Next.js"],
    ocrQuality: 98,
    crawledLinks: [
      { type: "GitHub", url: "github.com/priyasharma" },
      { type: "LinkedIn", url: "linkedin.com/in/priyasharma" },
    ],
  },
  {
    id: "2",
    name: "James Chen",
    role: "Full Stack Engineer",
    initials: "JC",
    fileName: "james_chen_resume.pdf",
    fileSize: "2.1 MB",
    status: "completed",
    progress: 100,
    currentAgent: "master",
    scores: { technical: 88, experience: 92, projects: 85, culture: 78, overall: 86 },
    redFlags: [{ severity: "low", text: "Frequent job changes" }],
    skills: ["Node.js", "Python", "AWS"],
    ocrQuality: 95,
    crawledLinks: [{ type: "GitHub", url: "github.com/jameschen" }],
  },
  {
    id: "3",
    name: "Maria Rodriguez",
    role: "UI/UX Designer",
    initials: "MR",
    fileName: "maria_rodriguez_resume.pdf",
    fileSize: "3.4 MB",
    status: "processing",
    progress: 45,
    currentAgent: "crawler",
    scores: { technical: 75, experience: 80, projects: 95, culture: 92, overall: 85 },
    redFlags: [],
    skills: ["Figma", "Design Systems", "React"],
    ocrQuality: 90,
    crawledLinks: [
      { type: "Portfolio", url: "mariarodriguez.design" },
      { type: "LinkedIn", url: "linkedin.com/in/mariarodriguez" },
    ],
  },
  {
    id: "4",
    name: "Alex Thompson",
    role: "Backend Developer",
    initials: "AT",
    fileName: "alex_thompson_resume.pdf",
    fileSize: "1.8 MB",
    status: "idle",
    progress: 0,
    currentAgent: null,
    scores: { technical: 95, experience: 70, projects: 80, culture: 85, overall: 83 },
    redFlags: [{ severity: "medium", text: "No relevant certifications" }],
    skills: ["Go", "Rust", "Kubernetes"],
  },
  {
    id: "5",
    name: "Sarah Kim",
    role: "DevOps Engineer",
    initials: "SK",
    fileName: "sarah_kim_resume.pdf",
    fileSize: "1.5 MB",
    status: "processing",
    progress: 60,
    currentAgent: "redflag",
    scores: { technical: 90, experience: 88, projects: 82, culture: 95, overall: 89 },
    redFlags: [],
    skills: ["Terraform", "CI/CD", "Azure"],
    ocrQuality: 97,
  },
  {
    id: "6",
    name: "David Park",
    role: "Mobile Developer",
    initials: "DP",
    fileName: "david_park_resume.pdf",
    fileSize: "2.3 MB",
    status: "completed",
    progress: 100,
    currentAgent: "master",
    scores: { technical: 82, experience: 78, projects: 90, culture: 88, overall: 84 },
    redFlags: [{ severity: "high", text: "Employment gap 2023-2024" }],
    skills: ["Swift", "Kotlin", "Flutter"],
    ocrQuality: 93,
    crawledLinks: [{ type: "GitHub", url: "github.com/davidpark" }],
  },
];

export const initialAgents: Agent[] = [
  {
    id: "intake",
    name: "Intake Agent",
    icon: "Inbox",
    color: "#4A90E2",
    status: "active",
    resumes: mockResumes.filter((r) => r.currentAgent === "intake" || (!r.currentAgent && r.status === "idle")),
    progress: 100,
  },
  {
    id: "ocr",
    name: "OCR Agent",
    icon: "ScanText",
    color: "#9B59B6",
    status: "active",
    resumes: mockResumes.filter((r) => r.currentAgent === "ocr"),
    progress: 75,
  },
  {
    id: "crawler",
    name: "Crawler Agent",
    icon: "Globe",
    color: "#1ABC9C",
    status: "active",
    resumes: mockResumes.filter((r) => r.currentAgent === "crawler"),
    progress: 50,
  },
  {
    id: "redflag",
    name: "Red Flag Agent",
    icon: "AlertTriangle",
    color: "#E74C3C",
    status: "active",
    resumes: mockResumes.filter((r) => r.currentAgent === "redflag"),
    progress: 30,
  },
  {
    id: "scoring",
    name: "Scoring Agent",
    icon: "BarChart3",
    color: "#F39C12",
    status: "idle",
    resumes: mockResumes.filter((r) => r.currentAgent === "scoring"),
    progress: 0,
  },
  {
    id: "master",
    name: "Master Agent",
    icon: "Crown",
    color: "#6C63FF",
    status: "active",
    resumes: mockResumes.filter((r) => r.currentAgent === "master"),
    progress: 90,
  },
];

export const mockActivities: ActivityEvent[] = [
  {
    id: "1",
    agent: "OCR Agent",
    message: "Processed 3 resumes with 98% accuracy",
    timestamp: "2 min ago",
    type: "processing",
  },
  {
    id: "2",
    agent: "Master Agent",
    message: "Ranked 12 candidates by overall score",
    timestamp: "5 min ago",
    type: "complete",
  },
  {
    id: "3",
    agent: "Crawler Agent",
    message: "Found GitHub profiles for 8 candidates",
    timestamp: "8 min ago",
    type: "processing",
  },
  {
    id: "4",
    agent: "Red Flag Agent",
    message: "Detected 2 potential concerns in batch #4",
    timestamp: "12 min ago",
    type: "handoff",
  },
  {
    id: "5",
    agent: "Intake Agent",
    message: "Received 5 new resume uploads",
    timestamp: "15 min ago",
    type: "processing",
  },
];

export const defaultPresets: WeightPreset[] = [
  { id: "1", name: "Balanced", technical: 25, experience: 25, projects: 25, culture: 25 },
  { id: "2", name: "Technical Focus", technical: 40, experience: 20, projects: 25, culture: 15 },
  { id: "3", name: "Culture First", technical: 20, experience: 20, projects: 20, culture: 40 },
];
