import { Package } from 'lucide-react'
import { IconType } from 'react-icons'
import { BiWater } from 'react-icons/bi'
import { BsBookmark, BsLightningCharge, BsTools } from 'react-icons/bs'
import {
  FaBook,
  FaCamera,
  FaCode,
  FaCoffee,
  FaGift,
  FaHatCowboy,
  FaIdBadge,
  FaLaptop,
  FaMedal,
  FaMusic,
  FaPaintBrush,
  FaPen,
  FaPencilAlt,
  FaPlane,
  FaShoppingBag,
  FaStickyNote,
  FaTicketAlt,
  FaTrophy,
  FaTshirt,
  FaUtensils,
} from 'react-icons/fa'
import { HiAcademicCap } from 'react-icons/hi'
import { IoGameController } from 'react-icons/io5'
import {
  MdCake,
  MdCardMembership,
  MdCelebration,
  MdMovie,
  MdSportsSoccer,
  MdWorkspacePremium,
} from 'react-icons/md'
import { RiLuggageCartLine } from 'react-icons/ri'

export const iconMap: Record<string, IconType> = {
  shirt: FaTshirt,
  tshirt: FaTshirt,
  't-shirt': FaTshirt,
  hat: FaHatCowboy,
  cap: FaHatCowboy,
  food: FaUtensils,
  meal: FaUtensils,
  lunch: FaUtensils,
  dinner: FaUtensils,
  breakfast: FaUtensils,
  coffee: FaCoffee,
  tea: FaCoffee,
  workshop: BsTools,
  seminar: HiAcademicCap,
  code: FaCode,
  coding: FaCode,
  programming: FaCode,
  computer: FaLaptop,
  tech: FaLaptop,
  technology: FaLaptop,
  sport: FaTrophy,
  sports: MdSportsSoccer,
  game: IoGameController,
  gaming: IoGameController,
  music: FaMusic,
  art: FaPaintBrush,
  dance: FaMusic,
  book: FaBook,
  books: FaBook,
  ticket: FaTicketAlt,
  pass: FaTicketAlt,
  party: MdCelebration,
  celebration: MdCelebration,
  birthday: MdCake,
  certificate: MdCardMembership,
  registration: FaIdBadge,
  travel: FaPlane,
  trip: FaPlane,
  photo: FaCamera,
  photography: FaCamera,
  video: FaCamera,
  movie: MdMovie,
  design: FaPencilAlt,
  hackathon: BsLightningCharge,
  admission: FaTicketAlt,
  entry: FaTicketAlt,
  badge: FaIdBadge,
  id: FaIdBadge,
  lanyard: FaIdBadge,
  sticker: BsBookmark,
  poster: FaCamera,
  banner: FaCamera,
  kit: RiLuggageCartLine,
  goodies: FaGift,
  swag: RiLuggageCartLine,
  bag: FaShoppingBag,
  bottle: BiWater,
  mug: FaCoffee,
  pen: FaPen,
  notebook: FaStickyNote,
  notepad: FaStickyNote,
  water: BiWater,
  drink: BiWater,
  snack: FaUtensils,
  merchandise: FaTshirt,
  merch: FaTshirt,
}

export const defaultIcons: IconType[] = [
  FaTrophy,
  FaGift,
  FaTicketAlt,
  FaLaptop,
  FaBook,
  FaMedal,
  FaCode,
  RiLuggageCartLine,
  MdWorkspacePremium,
  BsLightningCharge,
]

export const typeStyles: Record<
  string,
  { bg: string; text: string; border: string }
> = {
  seminar: {
    bg: 'bg-blue-500/10',
    text: 'text-blue-600',
    border: 'border-blue-500/30',
  },
  workshop: {
    bg: 'bg-amber-500/10',
    text: 'text-amber-600',
    border: 'border-amber-500/30',
  },
  conference: {
    bg: 'bg-indigo-500/10',
    text: 'text-indigo-600',
    border: 'border-indigo-500/30',
  },
  competition: {
    bg: 'bg-red-500/10',
    text: 'text-red-600',
    border: 'border-red-500/30',
  },
  meetup: {
    bg: 'bg-teal-500/10',
    text: 'text-teal-600',
    border: 'border-teal-500/30',
  },
  training: {
    bg: 'bg-cyan-500/10',
    text: 'text-cyan-600',
    border: 'border-cyan-500/30',
  },
  webinar: {
    bg: 'bg-sky-500/10',
    text: 'text-sky-600',
    border: 'border-sky-500/30',
  },
  hackathon: {
    bg: 'bg-orange-500/10',
    text: 'text-orange-600',
    border: 'border-orange-500/30',
  },
  concert: {
    bg: 'bg-pink-500/10',
    text: 'text-pink-600',
    border: 'border-pink-500/30',
  },
  fundraiser: {
    bg: 'bg-emerald-500/10',
    text: 'text-emerald-600',
    border: 'border-emerald-500/30',
  },
  networking: {
    bg: 'bg-violet-500/10',
    text: 'text-violet-600',
    border: 'border-violet-500/30',
  },
  internal: {
    bg: 'bg-slate-500/10',
    text: 'text-slate-600',
    border: 'border-slate-500/30',
  },
  other: {
    bg: 'bg-gray-500/10',
    text: 'text-gray-600',
    border: 'border-gray-500/30',
  },
}

export const typeIcons: Record<string, IconType> = {
  seminar: HiAcademicCap,
  workshop: BsTools,
  conference: FaLaptop,
  competition: FaTrophy,
  meetup: FaIdBadge,
  training: FaBook,
  webinar: FaLaptop,
  hackathon: BsLightningCharge,
  concert: FaMusic,
  fundraiser: FaGift,
  networking: FaIdBadge,
  internal: FaIdBadge,
  other: Package,
}

// ── Technical Skill Icons ─────────────────────────────────────────────────────
// Maps skill names (lowercase) to their brand/official icons from react-icons.
// Only technical skills — no soft skills like communication or Jira.

import {
  SiTypescript,
  SiJavascript,
  SiPython,
  SiGo,
  SiRust,
  SiCplusplus,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiScala,
  SiDart,
  SiElixir,
  SiLua,
  SiGnubash,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiNuxt,
  SiRemix,
  SiExpress,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpringboot,
  SiRubyonrails,
  SiLaravel,
  SiGraphql,
  SiTailwindcss,
  SiSass,
  SiBootstrap,
  SiMui,
  SiRedux,
  SiPrisma,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiSqlite,
  SiRedis,
  SiFirebase,
  SiSupabase,
  SiElasticsearch,
  SiNeo4J,
  SiApachekafka,
  SiRabbitmq,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiAnsible,
  SiJenkins,
  SiGithubactions,
  SiGitlab,
  SiCircleci,
  SiPrometheus,
  SiGrafana,
  SiNginx,
  SiLinux,
  SiGit,
  SiGithub,
  SiJira,
  SiConfluence,
  SiNotion,
  SiFigma,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiOpencv,
  SiHuggingface,
  SiJupyter,
  SiPandas,
  SiNumpy,
  SiPostman,
  SiSwagger,
  SiVim,
  SiNeovim,
  SiIntellijidea,
  SiWebstorm,
} from 'react-icons/si'

export const skillIcons: Record<string, IconType> = {
  // Languages
  typescript: SiTypescript,
  javascript: SiJavascript,
  python: SiPython,
  go: SiGo,
  golang: SiGo,
  rust: SiRust,
  'c++': SiCplusplus,
  cpp: SiCplusplus,
  php: SiPhp,
  ruby: SiRuby,
  swift: SiSwift,
  kotlin: SiKotlin,
  scala: SiScala,
  dart: SiDart,
  elixir: SiElixir,
  lua: SiLua,
  bash: SiGnubash,
  shell: SiGnubash,

  // Frontend Frameworks
  react: SiReact,
  'react.js': SiReact,
  reactjs: SiReact,
  nextjs: SiNextdotjs,
  'next.js': SiNextdotjs,
  next: SiNextdotjs,
  vue: SiVuedotjs,
  'vue.js': SiVuedotjs,
  vuejs: SiVuedotjs,
  angular: SiAngular,
  svelte: SiSvelte,
  nuxt: SiNuxt,
  'nuxt.js': SiNuxt,
  remix: SiRemix,

  // Backend Frameworks
  nodejs: SiNodedotjs,
  'node.js': SiNodedotjs,
  node: SiNodedotjs,
  express: SiExpress,
  'express.js': SiExpress,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  spring: SiSpringboot,
  'spring boot': SiSpringboot,
  'ruby on rails': SiRubyonrails,
  rails: SiRubyonrails,
  laravel: SiLaravel,
  graphql: SiGraphql,

  // CSS / UI
  tailwind: SiTailwindcss,
  'tailwind css': SiTailwindcss,
  tailwindcss: SiTailwindcss,
  sass: SiSass,
  scss: SiSass,
  bootstrap: SiBootstrap,
  'material ui': SiMui,
  mui: SiMui,
  redux: SiRedux,

  // Databases
  mongodb: SiMongodb,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  mysql: SiMysql,
  sqlite: SiSqlite,
  redis: SiRedis,
  firebase: SiFirebase,
  supabase: SiSupabase,
  elasticsearch: SiElasticsearch,
  neo4j: SiNeo4J,

  // Message Queues
  kafka: SiApachekafka,
  'apache kafka': SiApachekafka,
  rabbitmq: SiRabbitmq,

  // Cloud & Infrastructure
  docker: SiDocker,
  kubernetes: SiKubernetes,
  k8s: SiKubernetes,
  terraform: SiTerraform,
  ansible: SiAnsible,
  jenkins: SiJenkins,
  'github actions': SiGithubactions,
  gitlab: SiGitlab,
  circleci: SiCircleci,
  prometheus: SiPrometheus,
  grafana: SiGrafana,
  nginx: SiNginx,
  linux: SiLinux,

  // Version Control & Dev Tools
  git: SiGit,
  github: SiGithub,
  jira: SiJira,
  confluence: SiConfluence,
  notion: SiNotion,
  postman: SiPostman,
  swagger: SiSwagger,
  vim: SiVim,
  neovim: SiNeovim,
  intellij: SiIntellijidea,
  'intellij idea': SiIntellijidea,
  webstorm: SiWebstorm,

  // Design Tools
  figma: SiFigma,

  // AI / ML
  tensorflow: SiTensorflow,
  pytorch: SiPytorch,
  'scikit-learn': SiScikitlearn,
  sklearn: SiScikitlearn,
  opencv: SiOpencv,
  huggingface: SiHuggingface,
  'hugging face': SiHuggingface,
  jupyter: SiJupyter,
  pandas: SiPandas,
  numpy: SiNumpy,
}

// ── Skill category colors ────────────────────────────────────────────────────

export const skillCategoryColors: Record<string, { bg: string; text: string; border: string }> = {
  language: { bg: 'bg-blue-50', text: 'text-blue-700', border: 'border-blue-200' },
  framework: { bg: 'bg-violet-50', text: 'text-violet-700', border: 'border-violet-200' },
  database: { bg: 'bg-emerald-50', text: 'text-emerald-700', border: 'border-emerald-200' },
  cloud: { bg: 'bg-amber-50', text: 'text-amber-700', border: 'border-amber-200' },
  devops: { bg: 'bg-cyan-50', text: 'text-cyan-700', border: 'border-cyan-200' },
  tool: { bg: 'bg-gray-50', text: 'text-gray-700', border: 'border-gray-200' },
  ai_ml: { bg: 'bg-rose-50', text: 'text-rose-700', border: 'border-rose-200' },
  design: { bg: 'bg-pink-50', text: 'text-pink-700', border: 'border-pink-200' },
  other: { bg: 'bg-slate-50', text: 'text-slate-700', border: 'border-slate-200' },
}

// ── Helper to get skill icon ─────────────────────────────────────────────────

export function getSkillIcon(skillName: string): IconType | null {
  const normalized = skillName.toLowerCase().trim()
  return skillIcons[normalized] || null
}

// ── Dark mode variants for skill category colors ─────────────────────────────

export const skillCategoryColorsDark: Record<string, { bg: string; text: string; border: string }> = {
  language: { bg: 'dark:bg-blue-500/15', text: 'dark:text-blue-400', border: 'dark:border-blue-500/20' },
  framework: { bg: 'dark:bg-violet-500/15', text: 'dark:text-violet-400', border: 'dark:border-violet-500/20' },
  database: { bg: 'dark:bg-emerald-500/15', text: 'dark:text-emerald-400', border: 'dark:border-emerald-500/20' },
  cloud: { bg: 'dark:bg-amber-500/15', text: 'dark:text-amber-400', border: 'dark:border-amber-500/20' },
  devops: { bg: 'dark:bg-cyan-500/15', text: 'dark:text-cyan-400', border: 'dark:border-cyan-500/20' },
  tool: { bg: 'dark:bg-gray-500/15', text: 'dark:text-gray-400', border: 'dark:border-gray-500/20' },
  ai_ml: { bg: 'dark:bg-rose-500/15', text: 'dark:text-rose-400', border: 'dark:border-rose-500/20' },
  design: { bg: 'dark:bg-pink-500/15', text: 'dark:text-pink-400', border: 'dark:border-pink-500/20' },
  other: { bg: 'dark:bg-slate-500/15', text: 'dark:text-slate-400', border: 'dark:border-slate-500/20' },
}
